### ISSUE TITLE
Add a Field on Homepage "PD now indexes x% of PEPPOL"

### ISSUE THREAD

**Issue by clancger** [phax/peppol-directory#31] opened 2017-11-18 14:44 UTC
With ELMA being added, the % coverage of PD should already approach 90%, and while this number will drop if eg France is added to the SML and not yet to PD, I think it would be good to track the total no of SML entries vs PD entries and show the status.

**Comment by phax** [comment] 2017-11-18 21:11
Therefore I would need to know the number of ServiceGroups - therefore PD-SML intgegration is needed. Please contact OO :(

**Comment by clancger** [comment] 2017-11-18 22:41
Automation would be nice, but I'm sure a manual comparison of on date x, SML entries y, vs PD entries z = xx% would be fine too,

**Comment by phax** [comment] 2018-04-10 17:29
This is basically a duplicate of #12

**Closed by phax** 2018-04-10 17:29 UTC
